### ISSUE TITLE
Feature request: Please add an option for not syncing simultaneously when editing

### ISSUE THREAD

**Issue by Nil-Zil** [Jasonlhy/VSCode-Browser-Sync#2]
Hello! Thank you for your timely response last time. I wonder if there could be an option for not syncing simultaneously when editing html file? By now if I edit the hosted html, it will reload immediately after a change, which makes it reloading frequently. I hope this could be resolved by adding an option to reload it manually. I am not very sure but it seems to be `codeSync: false` according to [this](https://www.browsersync.io/docs/options#option-codeSync). Thank you!

**Comment by Jasonlhy** [comment]
@Nil-Zil So you want to use the synchronization function only? This may be better to make a breaking change to make the configuration as an object so that I don't need to add the configuration parameter one by one in the `package.json`.

For example, in the new version, the setting may look like:
```
"browserSync.config" : {
   "browser" : ["chrome", "firefox"]
}
```

**Comment by Nil-Zil** [comment]
Yes, that would be great! Then I can add something else if I need. Thank you!

**Comment by Jasonlhy** [comment]
@Nil-Zil Please update to 1.2.0, and change the setting to the new format to support more configuration option. 😄

**Comment by Nil-Zil** [comment]
I think it works. Thank you for this great extension!

**Comment by Jasonlhy** [comment]
Just let me know if you want need further enhancement.
