### ISSUE TITLE
Browsersync Config in Settings does not accept relative Paths

### ISSUE THREAD

**Issue by falco467** [Jasonlhy/VSCode-Browser-Sync#5]
Hi!

I would like to configure the list of watched files in my project - but the configuration of the "files"-Option only accepts absolute Paths, not relative Paths like entering in the command-box. It would be great to configure these settings in the workspace-config, so whoever checks out the project can start the extension without having to specify watch-files.

**Comment by Jasonlhy** [comment]
Because the API of browser sync only accepts absolute path (as far as I know). But I can add a config which automatically changes the relative path you specified in the workspace-config to absolute path.

**Comment by falco467** [comment]
Sounds good - you could just move the `map( path => cwd + path )` method down below the `Object.assign()` and change all paths, which are not absolute ( Paths starting with '/' or Paths starting with '[A-Z]:' For Drive-Letters on Windows )

**Comment by Jasonlhy** [comment]
Released version 1.3.0 which support relative path of files to the workspace root in the setting.

**Comment by falco467** [comment]
Tested it for some time, works like a charm - thank you!
